### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by The-Compiler** [repology/repology-webapp#101]
Hey! It looks like the repology.org website (194.67.206.223) [seems to be down](https://downforeveryoneorjustme.com/repology.org) - for me, it just times out currently.

**Comment by AMDmi3** [comment]
Yes, the hoster has serious problems and may in fact never come back up. If it's still down by tomorrow evening (UTC), I'll look into other hosting solutions. May take some more time to setup stuff from scratch.

**Comment by The-Compiler** [comment]
Ouch, that sucks. Best of luck and thanks for your work! :heart:

**Comment by AMDmi3** [comment]
I'm currently working on a new setup.

**Comment by AMDmi3** [comment]
Looks like we're up and running. No data was lost, and it may be that the new VPS is faster (quick benchmark shows 2x, but still have to setup monitoring to determine how this affects Repology update and web response times).
