### ISSUE TITLE
Sort packages by type

### ISSUE THREAD

**Issue by mikhailnov** [repology/repology-webapp#104]
It would be nice to be able to sort packages by type: rpm, deb etc.
Real usecase: I wanted to update log4cpp in ROSA and went to https://repology.org/project/log4cpp/versions
It would be nice if I could quickly see all RPM distros separately

**Comment by mikhailnov** [comment]
or maybe some higlighting with different colors

**Comment by AMDmi3** [comment]
This is out of repology scope. Use pkgs.org
