### ISSUE TITLE
Add per-repository feeds

### ISSUE THREAD

**Issue by AMDmi3** [repology/repology-webapp#112]
Very similar to per-maintainer feed, but for whole repository. Especially useful if repository does not have explicit maintainers. See repology/repology-updater#992 and repology/repology-updater#994.

**Comment by JuniorJPDJ** [comment]
This should be closed I bet?

BTW. Can you document somewhere every RSS feed types repology supports?

**Comment by AMDmi3** [comment]
> This should be closed I bet as it seems to be done?

Right.

> BTW. Can you document somewhere every RSS feed types repology supports?

Any idea where it can be documented to be visible to users?

**Comment by JuniorJPDJ** [comment]
I'd go with Docs and maybe some url just below page title for which this feed is created.
