### ISSUE TITLE
Fails to find the FreeBSD port "jucipp"

### ISSUE THREAD

**Issue by yurivict** [repology/repology-webapp#123]
The port ```editors/jucipp``` exists but Repology returns nothing for this name.

**Comment by AMDmi3** [comment]
https://repology.org/project/juci%2B%2B/versions

**Comment by yurivict** [comment]
When the user searches for "jucipp" (the name of the github repository), noting is found.

Search by "jucipp" should find https://repology.org/project/juci%2B%2B/versions

**Comment by AMDmi3** [comment]
There's an issue for this, please stop duplicating it.

**Comment by yurivict** [comment]
> please stop duplicating it.

I don't know about it. If the issue is a duplicate, it can be linked.

**Comment by AMDmi3** [comment]
> I don't know about it

You've submitted it yourself.
