### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by The-Compiler** [repology/repology-webapp#125]
Looks like the certificate for repology.org expired around 2h ago.

**Comment by N0rbert** [comment]
Firefox says:  
>The certificate expired on 16.04.2020 20:30. The current time is 16.04.2020 22:41.   
> Error code:   
>SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by The-Compiler** [comment]
Thanks for the quick fix and for all the work you do on Repology! :+1:
