### ISSUE TITLE
Request: make clear whether a package is PRE-installed on a distro

### ISSUE THREAD

**Issue by MagnusBrzenk** [repology/repology-webapp#139]
I'm interested to know what distros have tmux PRE-installed (not just installable). I can't tell this information from the [tmux page](https://repology.org/project/tmux/versions). If this information is not available from the API, then maybe I'll request that it be added. If it is available in the API, then please represent whether a package is pre-installed in the frontend somehow. Thanks.

**Comment by AMDmi3** [comment]
None of known repository provides such information, so this is not possible.

**Comment by waldyrious** [comment]
Cross-referencing https://github.com/repology/repology-updater/issues/494.
