### ISSUE TITLE
Sort lists after amount

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#143]
There are many lists that show the same information, with slightly variation. Like project Summaries, Package names, Homepages, Downloads, Categories, Licenses.

See for example: https://repology.org/project/wget/information

Assuming that the most popular entry is correct, we should sort it after the amount of occurrences and only list the first 3 or 5.

Example:

![Screenshot from 2020-07-14 15-24-52](https://user-images.githubusercontent.com/91113/87430974-3c1e7380-c5e6-11ea-9b6a-b8c8b36d49a1.png)

![Screenshot from 2020-07-14 15-28-38](https://user-images.githubusercontent.com/91113/87431336-c5ce4100-c5e6-11ea-8cf0-9b4fe2e04576.png)

That makes it easier to find the relevant information and makes the website cleaner.

**Comment by AMDmi3** [comment]
Assumption that most popular entry is correct is invalid. The most precise entry may have only one occurance as in given example.
