### ISSUE TITLE
Deduplicate Homepage URLs

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#144]
The listed homepage URLs have duplicated information. For example, when https works, we don't have to show the same URL with http.

Example: https://repology.org/project/boehm-gc/information

**Homepages**
http://hboehm.info/gc/ (2)
http://www.hboehm.info/gc (2)
http://www.hboehm.info/gc/ (14)
http://www.hpl.hp.com/personal/Hans_Boehm/gc/ (8)
https://github.com/ivmai/bdwgc
https://github.com/ivmai/bdwgc/
https://hboehm.info/gc/ (5)
https://www.hboehm.info/gc/ (13)

- Combine https and http (use https)
- Combine www and non-www (use non-www)
- Combine with and without trailing slash (use with)

Maybe remove https/http, www and try if we get the same content and add trailing slash and check and if that works, use it, even if no reporitory use it yet. It is the recommended URL form and commonly used.

**Homepages**
https://hboehm.info/gc/ (36)
http://www.hpl.hp.com/personal/Hans_Boehm/gc/ (8)
https://github.com/ivmai/bdwgc/ (2)

When a repository don't use the most popular URL, it could become a warning and recommendation to use it.

**Comment by AMDmi3** [comment]
URLs are conveyed as-is from packages.
