### ISSUE TITLE
Combine Downloads URLs

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#145]
Similar to https://github.com/repology/repology-webapp/issues/144, show recommended URL.

Example: https://repology.org/project/boehm-gc/information

**Downloads**
http://hboehm.info/gc/gc_source/gc-7.6.4.tar.gz
http://www.hboehm.info/gc/gc_source/gc-7.2.tar.gz
http://www.hboehm.info/gc/gc_source/gc-8.0.4.tar.gz (3)
http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.0.tar.gz
http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.1.tar.gz
http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.2.tar.gz
https://github.com/ivmai/bdwgc/releases/download/v7.6.12/gc-7.6.12.tar.gz
https://github.com/ivmai/bdwgc/releases/download/v7.6.6/gc-7.6.6.tar.gz
https://github.com/ivmai/bdwgc/releases/download/v7.6.8/gc-7.6.8.tar.gz
https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz (7)
https://github.com/ivmai/libatomic_ops/releases/download/v7.6.10/libatomic_ops-7.6.10.tar.gz
https://github.com/ivmai/libatomic_ops/releases/download/v7.6.6/libatomic_ops-7.6.6.tar.gz
https://hboehm.info/gc/gc_source/gc-7.6.0.tar.gz
https://hboehm.info/gc/gc_source/gc-8.0.4.tar.gz (3)
https://hboehm.info/gc/gc_source/libatomic_ops-7.6.6.tar.gz

- Use https when available
- Remove www subdomain when possible (same content)
- Use only latest version
- Use http instead of ftp?

**Downloads**
https://github.com/ivmai/bdwgc/releases/download/v8.0.4/gc-8.0.4.tar.gz (10)
https://hboehm.info/gc/gc_source/gc-8.0.4.tar.gz (7)
http://www.hpl.hp.com/personal/Hans_Boehm/gc/gc_source/gc-7.2.tar.gz (3)
https://github.com/ivmai/libatomic_ops/releases/download/v7.6.10/libatomic_ops-7.6.10.tar.gz (2)
https://hboehm.info/gc/gc_source/libatomic_ops-7.6.6.tar.gz

That makes it easier to find the relevant information and makes the website cleaner.

**Comment by AMDmi3** [comment]
URLs are conveyed as-is from packages.
