### ISSUE TITLE
projects: be able to use multiple maintainers in the advanced search

### ISSUE THREAD

**Issue by tormath1** [repology/repology-webapp#147]
Hi, 

I'd like to know if it's possible to [search](https://repology.org/projects/) `projects` using a list of multiple maintainers in the advanced mode.

From the API [spec](https://repology.org/api), we can see:
```json
{
    "repo": "freebsd",
    "srcname": "www/firefox",
    "binname": "firefox",
    "visiblename": "www/firefox",
    "version": "50.1.0",
    "origversion": "50.1.0_4,1",
    "status": "newest",
    "summary": "Widely used web browser",
    "categories": ["www"],
    "licenses": ["GPLv2+"],
    "maintainers": ["gecko@FreeBSD.org"],
    "www": ["http://www.mozilla.com/firefox"],
    "downloads": ["http://download.cdn.mozilla.net/pub/firefox/releases/50.1.0/source/firefox-50.1.0.source.tar.xz"]
}
```

which means `maintainers` is a list so it seems to be supported API side.

I'm using repology as a package maintainer and I have multiple accounts: my email address and the AUR pseudonyme. Which means, I need to perform 2 requests to fetch all the packages I maintain.

(maybe it already exists but I did not find any documentation :) ) 
 
Thanks for developing this useful tool !

**Comment by AMDmi3** [comment]
This is unlikely to be implemented. This would imply doing a large project query two times under the hood, which is slow and require code complication, while the same thing can be done by requesting two projects sets explicitly. Also, from the UI viewpoint, all advanced search conditions assume AND logic, while this one requires OR logic, which would introduce extra confusion.

**Comment by tormath1** [comment]
Hey @AMDmi3, 

Ok I understand, it was just a random question in my mind. I let you close the issue if you won't dig further !

**Comment by AMDmi3** [comment]
I'll think this over a bit more. Btw, you could also push AUR devs to publish more complete package metadata which contains maintainer emails, this would fix your original problem too.

**Comment by AMDmi3** [comment]
As mentioned, this is not going to be implemented as a standalone feature (however if at some point we reimplement the search with support for a complex search language like one github supports, this would probably be implemented as a by-product).

However, right now there's an [option](https://github.com/repology/repology-updater/blob/master/maintainers.yaml) to manually merge different maintainer accounts.

**Comment by AMDmi3** [comment]
@tormath1 Would you like a maintainer merge?
