### ISSUE TITLE
"problems" endpoint does not return problems anymore?

### ISSUE THREAD

**Issue by matthiasbeyer** [repology/repology-webapp#149]
```
curl https://repology.org/api/v1/repository/freebsd/problems | jq | less -R
```

I assume what is documented:

> Output is an array of entries of the following format:
> 
> {
>     "repo": "freebsd",
>     "name": "abby",
>     "effname": "abby",
>     "maintainer": "ports@freebsd.org",
>     "problem": "Homepage link \"https://code.google.com/archive/p/abby/\" points to Google Code which was discontinued. The > link should be updated (probably along with download URLs). If this link is still alive, it may point to a new project homepage."
> }

But instead I get packages as return value:

```json
[
  {
    "id": 215185793,
    "repo": "freebsd",
    "family": "freebsd",
    "subrepo": null,
    "name": null,
    "srcname": "games/0verkill",
    "binname": "0verkill",
    "visiblename": "games/0verkill",
    "projectname_seed": "0verkill",
    "trackname": "games/0verkill",
    "origversion": "0.16",
    "rawversion": "0.16_2",
    "arch": null,
    "maintainers": [
      "mich@freebsd.org"
    ],
    "category": "games",
    "comment": "Bloody 2D action deathmatch-like game in ASCII art",
    "homepage": "http://artax.karlin.mff.cuni.cz/~brain/0verkill/",
    "licenses": null,
    "downloads": null,
    "extrafields": null,
    "effname": "0verkill",
    "version": "0.16",
    "versionclass": 1,
    "flags": 0,
    "shadow": false,
    "flavors": null,
    "branch": null,
    "cpe_vendor": null,
    "cpe_product": null,
    "cpe_edition": null,
    "cpe_lang": null,
    "cpe_sw_edition": null,
    "cpe_target_sw": null,
    "cpe_target_hw": null,
    "cpe_other": null,
    "binnames": null,
    "maintainer": "mich@freebsd.org",
    "type": "homepage_dead",
    "data": {
      "url": "http://artax.karlin.mff.cuni.cz/~brain/0verkill/",
      "code": 500
    }
  },
[...]
]
```

What happened?

**Comment by matthiasbeyer** [comment]
No comment?

**Comment by AMDmi3** [comment]
I've updated and just deployed the docs. In short:
- problems data is still returned, though the format had changed to `{"type":"string constant", "data":{dict of additional information}}`. String messages are no longer generated as they are redundant and not flexible. With the new format you have ready to use structured details, such as actual HTTP codes for "dead homepage" problems
- other fields are raw package fields, in the current implementation they are needed to generate links to packages (done on the fly with templates defined in repo configs) as seen on the problems page (same SQL query is in fact used for the site and API). API consumers may use these to precisely identify the package which generated the problem (with `name`, `srcname`, `binname`, `binnames`, `rawversion` etc. fields) in a repository specific way - I'm still puzzled on how to do this in a more generic way. It would also make sense to trim large and unneeded fields such as comment and URLs from here to reduce API output size and speed it up a bit.
