### ISSUE TITLE
Introduce some kind of popularity contest/popcon data for packages?

### ISSUE THREAD

**Issue by Ekleog** [repology/repology-webapp#159]
Hello people!

Here is an idea that may very well be crazy, but: what would you think about introducing some sort of distro ranking by availability of packages taken from a popularity contest?

Such a ranking would inherently be biased (eg. because picking the distro from which the popcon will be used will by definition give this distro a 100% success rate, plus popcon is usually opt-in, etc…), but IMO it could help show a bit to distro maintainers where effort might be fruitful. And well, we at nixpkgs are currently leading the charts mostly thanks to having thousands of packages that are auto-generated from upstream repositories, so… the system is currently biased in our favor by counting even little-used packages :sweat_smile: 

For the context, I thought about this in this discussion: https://discourse.nixos.org/t/nixpkgs-has-been-the-largest-repository-for-months/10667/8 (where I tried to do something like that by hand in a really badly-implemented way, and then thought that this might be something you could find useful to introduce directly to repology)

What do you think about that idea? Anyway, thank you for repology! It's great already :)

**Comment by AMDmi3** [comment]
No, sorry. Repology is about facts, not opinions, especially biased ones.

**Comment by Atemu** [comment]
I think popularity is factual enough of a metric, it's just a matter of how it's quantified.

Relying on a single source is obviously bad but there are multiple sources one could use.

Popcorn has been mentioned, the AUR has a popularity metric, stars on GH represent popularity fairly well IME and I'm sure there are more.  
Libraries.io actually lists many such properties that could be used to quantify popularity like information extracted from GH or dependent packages.  
Another interesting metric for judging popularity would be number of downloads, pypi and rubygems offer these for example.

Obviously none of these metrics are perfect (especially not on their own) but as long as their limits are clear, they could be a very useful tool IMO.

For example, filtering projects that aren't in a certain but in at least one other repository family is only semi-helpful currently as that gives you a huge list of packages, most of which probably have very little users, sorted alphabetically.  
If I could then sort that list by GH stars/forks/watchers, popularity in the AUR or number of downloads on PyPi instead, that'd be make the list a lot more valuable.

Judging overall popularity would have to be fairly opinionated but just exposing various popularity metrics and letting the user choose what they care about would be just as factual as the current repology IMO.
