### ISSUE TITLE
Determination of "newest version" fails for some applications

### ISSUE THREAD

**Issue by dschrempf** [repology/repology-webapp#166]
The determination of the correct newest version fails for some applications. For example, `dupeguru` is reported as out of date for all distributions but for a distribution using a commit hash (or date):

![2021-04-24_14-37](https://user-images.githubusercontent.com/5596239/115959118-c519f200-a50a-11eb-9c2d-949c83f4e398.png)

**Comment by AMDmi3** [comment]
This is expected. Each individual case should be reported and fixed with a rule.
