### ISSUE TITLE
Add info about linux distros

### ISSUE THREAD

**Issue by don-rumata** [repology/repology-webapp#168]
Can you add information about distribution releases, such as: "title", "release", "supported/no", etc?

like https://changelogs.ubuntu.com/meta-release, but for all.

**Comment by AMDmi3** [comment]
Not really, I don't see a need for and don't want to maintain this data.

**Comment by AMDmi3** [comment]
What goal would it achieve?

**Comment by don-rumata** [comment]
I can check the availability of docker images (e.g. at https://github.com/diodonfrost/docker-ansible) for my playbooks on ansible.

**Comment by AMDmi3** [comment]
This is out of repology scope
