### ISSUE TITLE
"in repositories" badge count is too low.

### ISSUE THREAD

**Issue by nschloe** [repology/repology-webapp#172]
[One of my packages](https://repology.org/project/pygalmesh/badges) is in 18 repos

![screenshot](https://user-images.githubusercontent.com/181628/118360978-8ddab600-b589-11eb-8e10-b7021c55b7fa.png)

but "in repos" only shows one:

![screenshot](https://user-images.githubusercontent.com/181628/118360999-a64ad080-b589-11eb-8547-46c52cc48b45.png)

This is because they all descend from Debian.

"1" is a bit of a sad number to show off though, and it doesn't really reflect how widely available the package is in the ecosystem. I would suggest that "in repos" shows the same number of distros as appearing in the detailed view.

**Comment by AMDmi3** [comment]
It works as intended and you've pretty much explained why yourself - it's in fact just a single package wrapped in differently colored wrappers. Counting it differently would convey incorrect information for it really _is_ only packaged once and not widely spread at all, and make comparison unfair for packages packaged in ecosystems which don't have such variety repository branches and clones.
