### ISSUE TITLE
Add links to PyPI homepages

### ISSUE THREAD

**Issue by sbraz** [repology/repology-webapp#173]
Hi,
I don't see links to PyPI homepages for relevant packages, e.g. for https://repology.org/project/python:tempora/versions

However, there is a link declared here, is it missing something?
https://github.com/repology/repology-updater/blob/f52410c9d355264b05a0da380e2848fda28e475e/repos.d/modules/pypi.yaml#L22-L24

**Comment by AMDmi3** [comment]
There's a place in the code which picks a single link for a package to use on that page, and required link type was missing there. Thanks!

**Comment by sbraz** [comment]
Thanks @AMDmi3. Out of curiosity, when there are several `packagelinks`, are they displayed somewhere else? I couldn't find them.

**Comment by AMDmi3** [comment]
Sure, on `Packages` and `Information` subpages for a project.
