### ISSUE TITLE
Some packages are shown with a lot of repetitive versions

### ISSUE THREAD

**Issue by yurivict** [repology/repology-webapp#186]
For example see this screenshot:
![image](https://user-images.githubusercontent.com/271906/150914049-b0283e9f-6779-4ba0-bfb0-269a9d5450d1.png)

**Comment by yurivict** [comment]
@AMDmi3 
The problem still exists. Many versions of some python packages are shown from PyPI, for example [here](https://repology.org/project/python:cirq-aqt/versions) instead of just one version.

**Comment by AMDmi3** [comment]
There is no problem, works as intended.
