### ISSUE TITLE
Repository size graph cuts off some repository names

### ISSUE THREAD

**Issue by alyaeanyx** [repology/repology-webapp#188]
See screenshot
![Screenshot from 2022-03-02 19-47-13](https://user-images.githubusercontent.com/74795488/156428244-5b5f2ac9-97c6-4e90-80e6-1790b342683e.png)

**Comment by AMDmi3** [comment]
I don't like the idea of wasting space on already crowded graphs for a little cosmetic gain.
It would make more sense to instead place the labels to the left of points in the rightmost 10% area.

Can be done by conditionally setting "text-anchor" to "end" and inverting the X offset when generating labels:
https://github.com/repology/repology-webapp/blob/479ca59e0cf356e0bf42961d130a13289c993e2e/repologyapp/views/graphs_map.py#L135-L138

**Comment by alyaeanyx** [comment]
Yeah, that makes sense. I've updated my pull request accordingly.
