### ISSUE TITLE
API Questions!

### ISSUE THREAD

**Issue by vsoch** [repology/repology-webapp#190]
Hey @AMDmi3 ! Thanks for making repology! A quick question - I'm exploring the API and it looks like I can get basic package info:

```
'firefox-privacy': [{'repo': 'noir',
   'subrepo': 'extra',
   'name': 'firefox-privacy',
   'visiblename': 'firefox-privacy',
   'version': '1.0',
   'maintainers': ['m_matongo@icloud.com'],
   'status': 'unique',
   'origversion': None}]
```
Are you planning to have support to show more metadata, e.g., dependencies (and the other kinds of stuff we provide to repology?) https://spack.github.io/packages/data/repology.json. If not no worries - I can look at libraries.io or similar. Thank you!

**Comment by AMDmi3** [comment]
Dependencies are not processed by Repology yet.

**Comment by vsoch** [comment]
Gotcha, thanks!
