### ISSUE TITLE
Allow selecting number of columns in badges.

### ISSUE THREAD

**Issue by pktiuk** [repology/repology-webapp#197]
Badges for apps having many packages may be a bit to tall to be radaable and look good in places like README.

<details>
<summary><b>Example</b></summary>

Firefox
<a href="https://repology.org/project/firefox/versions">
    <img src="https://repology.org/badge/vertical-allrepos/firefox.svg" alt="Packaging status">
</a>
</details>

It would be good to allow setting number of columns in such a badge. It would greatly improve readability.

**Comment by AMDmi3** [comment]
Already implemented
