### ISSUE TITLE
A badge that displays repository information

### ISSUE THREAD

**Issue by firasuke** [repology/repology-webapp#199]
Hey there,

I've noticed that Repology provides [badges for projects](https://repology.org/project/unit/badges), but does it also provide badges for repositories? Would it be possible to create a badge showcasing the total number of packages, the ones that are up-to-date (with percentage option), the ones that are outdated, the ones with problems, and the current number of maintainers?

Thanks!

**Comment by AMDmi3** [comment]
Duplicate of #29
