### ISSUE TITLE
incorrect version shown marks package ignored (uqm-content)

### ISSUE THREAD

**Issue by mnalis** [repology/repology-webapp#200]
On https://repology.org/project/uqm/versions#debian_12

package `uqm-content` is shown as version `0.8.0+deb` with status `ignored`, which according to docs means:

> version is ignored and excluded from comparison for some other reason (e.g. snapshots).

However, correct package version is (and has been for months) `0.8.0+deb-1` as evidented by https://packages.debian.org/bookworm/uqm-content, but it seems to be misdetected by repology by dropping `-1` at the end. It is no snapshot, but normal final release of the package.

Could it be fixed if the problem is in repology, or is the problem upstream in Debian?

**Comment by AMDmi3** [comment]
Upstream version is `0.8.0`, neither `0.8.0+deb` nor `0.8.0+deb-1` is correct and usable by repology. Tailing `-N` component is dropped from deb versions as it denotes a debian revision and is not usable for version comparison, but it does not affect this case.
