### ISSUE TITLE
About project deprecation information

### ISSUE THREAD

**Issue by chenrui333** [repology/repology-webapp#203]
I think it would be good to surface the project deprecation information for package maintainer, but I could not find such info on the site yet, let me know I missed anything. Thanks!

**Comment by AMDmi3** [comment]
Please elaborate what you're trying to do

**Comment by AMDmi3** [comment]
Timeout, I do not understand the proposal

**Comment by chenrui333** [comment]
mostly just release cycle thing. like node@10, node@12 deprecations if you know what i mean (it would be helpful to capture on the site), let me know if that makes sense.

**Comment by AMDmi3** [comment]
It does not.
