### ISSUE TITLE
DeprecationWarning: getsize is deprecated and will be removed in Pillow 10

### ISSUE THREAD

**Issue by tocic** [repology/repology-webapp#211]
Running the tests produces the following warning:

```
DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
```

https://github.com/repology/repology-webapp/blob/7495c992194294ae4302a8879ba7faa9659348c3/repologyapp/fontmeasurer.py#L52

**Comment by AMDmi3** [comment]
Fixed, but the fact that the new method returns significantly different results on FreeBSD and Ubuntu is worrying. Should be investigated at some point.
