### ISSUE TITLE
Autorefresh in Recent CVEs and CPE bindings doesn't work as expected

### ISSUE THREAD

**Issue by tocic** [repology/repology-webapp#213]
Clicking on the `Enable` button doesn't switch it to the `Disable` button. Instead, the `Published` column is changed.

https://repology.org/security/recent-cves?autorefresh=1

![autorefresh](https://user-images.githubusercontent.com/22129543/218025790-18e64757-02a9-4371-88fa-1194f58c029b.gif)

**Comment by AMDmi3** [comment]
> Clicking on the Enable button doesn't switch it to the Disable button.

Confirmed. Support for `autorefresh` var in the view is missing.

> Instead, the Published column is changed

This is somewhat expected - it just blinks as UTC dates are converted to local timezone after the page loads. There may be unrelated problem if it stays at `UTC` though. In fact it would be nice to convert dates even before they are rendered, but I currently dunno how to do that.
