### ISSUE TITLE
format idea: badge (abbreviated, most recent OS releases)

### ISSUE THREAD

**Issue by nbehrnd** [repology/repology-webapp#214]
Visiting the entry about [clawsker](https://repology.org/project/clawsker/versions), I noticed some of the entries reach far back into history.  Examples include Ubuntu LTS (current 22.10, yet equally back till 14.04), or Fedora (current 37, yet equally back till 26).  So the normal "full" badge would contain entries maybe not this much of interested for those maintaining a contemporary installation.  To use

```
[![Packaging status](https://repology.org/badge/vertical-allrepos/clawsker.svg)](https://repology.org/project/clawsker/versions)
```

yields 

[![Packaging status](https://repology.org/badge/vertical-allrepos/clawsker.svg)](https://repology.org/project/clawsker/versions)

Open to discussion is the suggestion to offer a badge in an additional format to consider only the most recent Linux releases per distribution which did not reach the end of support.  E.g., for Ubuntu, to show the last non LTS release, and the last LTS.  One may argue if 14.04/16.04 mentioned [here](https://en.wikipedia.org/wiki/Ubuntu#Releases) as covered by *Extended security updates* still is frequently demanded.

In case of Fedora 26, which was released 2017-07-11, this reached its end of live 2018-05-29 ([reference](https://en.wikipedia.org/wiki/Fedora_Linux_release_history)) where

> a version of Fedora is usually supported for at least 13 months, possibly longer.

([reference](https://en.wikipedia.org/wiki/Fedora_Linux#Releases))

**Comment by AMDmi3** [comment]
We have `exclude_unsupported` parameter, it's documented. It seems to do just what you want, and I think it makes sense to switch Ubuntu from ESM to general releases EoL dates which will trim it even more.

| default |  `?exclude_unsupported=1` |
|-|-|
| ![Packaging status](https://repology.org/badge/vertical-allrepos/clawsker.svg) | ![Packaging status](https://repology.org/badge/vertical-allrepos/clawsker.svg?exclude_unsupported=1) |
