### ISSUE TITLE
repology and distrochooser?

### ISSUE THREAD

**Issue by ghost** [repology/repology-webapp#216]
Hi everyone.

I wonder if there would be interest in a partnership between repology and distrochooser. 

Distrochooser is a tool that helps people choose Linux more consciously. 

I ask about this need, because an initial doubt with those who like linux is related to the update cycle, as well as package managers or even useful and general information on the similarity and difference between one or more packages or repositories in different linux distros.

*Would there be interest in a partnership between repology and distrochooser?*

**Comment by AMDmi3** [comment]
What kind of partnership do you propose?
