### ISSUE TITLE
Homebrew project distinction

### ISSUE THREAD

**Issue by chenrui333** [repology/repology-webapp#222]
As linuxbrew-core merged into homebrew-core [long time back](https://github.com/Homebrew/linuxbrew-core/commit/51b47956b0713413d134a533759a1873e53a3578), homebrew-core supports both osx and linux, not sure if it is a good idea to differentiate the support notations on the site. Let me know if that makes sense!

**Comment by AMDmi3** [comment]
Please elaborate. Repology does not differentiate linuxbrew since 2021.

**Comment by AMDmi3** [comment]
It does not. Please give an example of package in question and what exactly should be changed for it.
