### ISSUE TITLE
Fetch all outdated packages in a repository

### ISSUE THREAD

**Issue by osalbahr** [repology/repology-webapp#225]
Hi! Is there a way to grab only the names of all outdated packages in a certain repository? Something similar to `/api/v1/repository/freebsd/problems` in https://repology.org/api.

I tried `/api/v1/repository/freebsd/outdated` but it's not a valid API endpoint. The `problems` endpoint is the only one in the form of `/api/v1/repository/*/*` I could find in https://github.com/repology/repology-webapp/blob/master/repologyapp/views/api.py#L118. Any help would be appreciated.

**Comment by osalbahr** [comment]
Thank you! I must've missed that section.

**Comment by osalbahr** [comment]
I noticed that in https://repology.org/api/v1/projects/?inrepo=homebrew&outdated=on, `ca-certificates` is mentioned 708 times. Is there a supported way to get the output have the names only once? Like in https://repology.org/projects/?inrepo=homebrew&outdated=1 (there's only 511 of them). I'm now thinking to try to manually filter the JSON

<img width="928" alt="Screenshot 2023-07-05 at 10 46 18 AM" src="https://github.com/containers/podman.io/assets/54853250/bd059912-4b77-44f9-838d-36c2f7ffd785">

***

Side note: there isn't really a practical reason for this. Just practicing API calls and text processing, and as a side effect get the most used outdated package (by cross-referencing with https://formulae.brew.sh/analytics/install/365d/). Let me know if there is a more suitable platform than opening an issue here. I opened an issue only because there's no https://github.com/orgs/Repology/discussions.

**Comment by osalbahr** [comment]
> That's by design. It filters projects by given condition, then returns all packages for these projects. You have to filter output to only have packages for specific repository.

Is that not what `inrepo=homebrew` does? Or how should I filter for it?

**Comment by AMDmi3** [comment]
Like I've said, inrepo selects projects present in homebrew and returns all packages in all repositories for these projects. If you want homebrew packages, you need to take ones with repo=homebrew

**Comment by osalbahr** [comment]
Oh, perfect. Thx again!
