### ISSUE TITLE
Badge request: custom version compare

### ISSUE THREAD

**Issue by mschubert** [repology/repology-webapp#228]
Thanks for creating/maintaining repology including the web app! It's a great tool for me to track the package versions I maintain for the Archlinux AUR to see when I should update the PKGBUILDS ([repository here](https://github.com/mschubert/PKGBUILDs)).

For this, I've added badges that query the AUR version, which works great to get this overview (according to the [usage docs](https://repology.org/tools/project-by)):

```
[![toolname](https://repology.org/badge/version-for-repo/aur/toolname.svg?header=toolname)]
```

![image](https://github.com/repology/repology-webapp/assets/442360/23860253-7770-4b3a-a40f-75d1ff422feb)

I'd like to create badges for a [gentoo overlay that I maintain](https://github.com/mschubert/overlay) as well, however, the overlay is not tracked by repology (which I think is fine, it's mostly personal use).

However, I'd need to check if my provided version (let's say, `snakemake=7.30.2`) is still up-to-date with other distributions.

Would it be possible to add a custom version compare badge, similar to this?

```
[![toolname](https://repology.org/badge/version-for-repo/custom/toolname.svg?header=toolname&version=7.30.2)]
```

**Comment by AMDmi3** [comment]
Sorry, not doing this. We discourage private repositories, as well as this kind of badge usage, as it generates extra spike load on the server. However, providing a maintainer badge, e.g. https://repology.org/projects/?maintainer=mschu@aur&inrepo=aur via in badge form makes sense (#252).
