### ISSUE TITLE
Add a way to query multiple packages

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [repology/repology-webapp#23]
I'd like to be able to see a table with
https://repology.org/metapackage/extra-cmake-modules/badges
and 
https://repology.org/metapackage/qt5-base/badges
together so it would be easier to find something like 
"If i require Qt 5.8 which is the maxmium extra-cmake-modules i can require?"

**Comment by AMDmi3** [comment]
Should be covered by matrix badges (repology/repology-rs#100) and third party tools https://github.com/woju/gramine-deps-table (see woju/gramine-deps-table#1). May implement something similar in Repology, but not in the near future.
