### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by kbdharun** [repology/repology-webapp#232]
Hi, similar to https://github.com/repology/repology-webapp/issues/101, the website <https://repology.org> seems to be down now. 

Can confirm the same issue is experienced by my friends across the globe. [This site](https://www.saashub.com/repology-status) suggests the site has been down for the past 2 hours and I noticed this when there was a broken badge in a repo's README.

**Comment by AMDmi3** [comment]
Hosting payment issues, fixed.

**Comment by kbdharun** [comment]
> Hosting payment issues, fixed.

Thanks ❤️ .
