### ISSUE TITLE
repology.org is down

### ISSUE THREAD

**Issue by mikaello** [repology/repology-webapp#241]
It seems like the repology.org website is down:

```
$ curl --verbose https://repology.org/
*   Trying 185.185.68.145:443...
*   Trying 2a0a:2b41:94:cb5e:::443...
* Immediate connect fail for 2a0a:2b41:94:cb5e::: Cannot assign requested address
^C
```

The first time we got errors in our logs was 20/03/2024 19:15:38, but I haven't checked the website until now.

**Comment by AMDmi3** [comment]
There were no recent downtimes. `Cannot assign requested address` is your local error.

**Comment by mikaello** [comment]
You are absolutely right, it was a network problem on my side that caused this, sorry for the noise.
