### ISSUE TITLE
API returns HTML in pages for blocked clients

### ISSUE THREAD

**Issue by SMillerDev** [repology/repology-webapp#242]
It seems Homebrew was blocked as an API consumer, so we'll see what we can do to behave better there.
But I did notice that the API returns an nginx HTML error page in such cases instead of returning JSON, 
which isn't documented anywhere and made the Homebrew parsing misbehave when it encountered the HTML.

Could you add this behaviour to the docs or, even more appreciated, make it return some JSON formatted error?

Thanks for all the effort in running Repology, it's much appreciated as a package maintainer!

---

Ref: https://github.com/Homebrew/brew/issues/17021

**Comment by AMDmi3** [comment]
Please provide your source IP, target endpoint and user agent.

**Comment by SMillerDev** [comment]
> Please provide your source IP, target endpoint and user agent.

The call is part of the brew package manager, so the source IP can be anything. 
An example target endpoint is: https://repology.org/api/v1/project/mtbl
User agent: `Homebrew/4.2.16-69-gfcc190b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0`

Called as:
```sh
/usr/bin/env /opt/homebrew/opt/curl/bin/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16-69-gfcc190b\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 14.4.1\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --location --silent https://repology.org/api/v1/project/mtbl
```

**Comment by AMDmi3** [comment]
Fixed by only blocking `curl/XXX`, and not cases of proper user agents where curl version is included.

> Could you add this behaviour to the docs or, even more appreciated, make it return some JSON formatted error?

No. You should not care of that because all you need is to check HTTP code.
