### ISSUE TITLE
Repology data as linked data (RDF)

### ISSUE THREAD

**Issue by Natureshadow** [repology/repology-webapp#251]
I would like to use repology information for comparisons with data I collect from systems. My data is collected as [RDF](https://www.w3.org/TR/rdf11-primer/) triples, the core of the semantic web and [linked data](https://en.wikipedia.org/wiki/Linked_data).

It would, generally, be helpful if Repolofy data were available as RDF (to be served alongside the web pages).

Has this already been discussed / considered? And would a contribution to add linked data information potentially be considered?

**Comment by Natureshadow** [comment]
I just found https://github.com/repology/repology-exports, which seems to be used to update linked data in Wikidata. I am not sure how complete it is, though.

**Comment by AMDmi3** [comment]
repology-exports has never taken off, Wikidata was updated by https://github.com/repology/repology-wikidata-bot at some point.

> I would like to use repology information for comparisons with data I collect from systems. My data is collected as [RDF](https://www.w3.org/TR/rdf11-primer/) triples, the core of the semantic web and [linked data](https://en.wikipedia.org/wiki/Linked_data).

Please explain your idea further. Which endpoints, which data, to whom would it be useful?

> Has this already been discussed / considered?

No. 

> And would a contribution to add linked data information potentially be considered?

Unlikely unless there's enough public demand.

**Comment by AMDmi3** [comment]
> I am not sure whether the concept of RDF and linekd data is well known to you; it seems that you somehow mix it up with SPARQL (a query protocol for RDF statements).

I understood it as you propose exposing Repology data as RDF triples. Am I mixing it up with SPARQL?

> Linked data itself does not need an "endpoint". Adding linked data support to Repology does not need support for any new server-side code at all. In the simplest case, it simply means adding some special attributes to the HTML markup of existing pages. Going a bit further, it would mean exposing data as a plain file next to the HTML version, e.g. as JSON-LD or Turtle.

You haven't answered my questions. Which endpoints? You've already mentioned embedding it into HTML endpoints and creating separate JSON-LD/Turtle ones. Do you propose both, or which is preferred? For the note, I don't like idea of adding it to HTML, as it makes HTML needlessly heavier for human consumers, and wastes resources on needless HTML generation for machine consumers. Also which endpoints apart from projects, as Repology has information on maintainers, repositories, packages, and events. Which data (which specific project/package fields), how exactly would it be used? Whole user story please.

> Basically, this makes Repology data useful for everyone who wants to use it in a machine-readable form – for example, to compare it with information on package versions collected locally.

That's still too abstract. Which specific applications are able to consume RDF data from Repology?

**Comment by AMDmi3** [comment]
Timeout

**Comment by Natureshadow** [comment]
>Timeout

😅🤦🏼
