### ISSUE TITLE
[Feature] Badge color can indicate closeness to stable (represented by a reddish shade of green in badge color-coded color)

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-webapp#256]
**Observation**: When a version change occurs, the badge color of the repository that is the most up to date will turn green. This subsequently turns the rest of the entries red to show they are not up to date.. 

**Difficulty**: What occurs is that it's hard to quickly differentiate what repositories are immediately behind the stable and which are grossly behind. They all turn red. This is also very pronounced in large/long badges.

**Ask**: A way to differentiate repos that are immediately behind contrasted via color-coding from the ones grossly behind.

**Proposal**: the color or the repos immediately behind new stable should be a reddish-green color-code to differentiate from hard red.

**Comment by AMDmi3** [comment]
What makes previous release special so you want to differentiate it from older releases?
What if upstream tags two releases in a row?

**Comment by luzpaz** [comment]
If say, you have a very large badge that consists of many packagers that are **not** consistently up to date while there are maybe 6 or 7 of them that are - no matter what they all immediately marked red and it's a bit tedious and scan through the list to identify which is which. The reason this would be helpful is to perhaps differentiate which downstream packagers should be contacted (the less-engaged ones) in order to bring their versions up to date,  while the more engaged packagers will probably not need to be contacted. 

> What if upstream tags two releases in a row?  

2 options come to mind, have some logic that checks a designated threshold timer (48 hours) that can accommodate this or fallback to the current approach in use.

**Comment by AMDmi3** [comment]
> is to perhaps

So this is hypothetical use case?

> which downstream packagers should be contacted

Why would you use badges for that? There are maintainers listed on package versions and packages pages.

**Comment by luzpaz** [comment]
>> is to perhaps
> So this is hypothetical use case?

Another way to say 'for instance...'

> Why would you use badges for that? There are maintainers listed on package versions and packages pages.

Most maintainers want to be contacted via their respective repository workflow (bugtracker, notification system etc..) and don't appreciate being emailed directly).

**Comment by luzpaz** [comment]
Nevermind. 

Closing.
