### ISSUE TITLE
Add badges for repositories

### ISSUE THREAD

**Issue by matthewbauer** [repology/repology-webapp#29]
I think some repositories might want to have badges. Something like the information on the statistics page:

https://repology.org/statistics

useful ones would be:
- x total packages
- x% fresh

We would definitely like something like this for https://github.com/NixOS/nixpkgs

**Comment by firasuke** [comment]
> Thanks for the suggestion! Since there's a demand, I'll do it.

Is this still relevant today? Or is this such a badge not planned?

**Comment by AMDmi3** [comment]
How's about this:
![FreeBSD](https://repology.org/badge/repository-big/freebsd.svg)
![Debian Unstable](https://repology.org/badge/repository-big/debian_unstable.svg)
![Nix unstable](https://repology.org/badge/repository-big/nix_unstable.svg)

**Comment by firasuke** [comment]
Yup, this is exactly what we are asking for!
