### ISSUE TITLE
Need version badges accessible by original package name

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-webapp#61]
Ex. In the [FreeCAD package](https://repology.org/project/freecad/versions) it shows that the AUR has 3 different packages `freecad`, `freecad-appimage`, and `freecad-git`  
How then can I generate a badge for each of these? Right now only the freecad-git badge is displayed in the [badges page](https://repology.org/project/freecad/badges)

**Comment by AMDmi3** [comment]
Done as https://repology.org/tools/project-by
