### ISSUE TITLE
Add legend to repositories updates page

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#85]
What does this symbols mean?

![Screenshot from 2019-10-23 14-40-14](https://user-images.githubusercontent.com/91113/67393721-38077d00-f5a3-11e9-913c-f4b044a50e0c.png)

Please add a legend to the https://repology.org/repositories/updates page.

**Comment by davidak** [comment]
Thanks for the fast fix!

▶ is missing. i assume it means currently processing...

![Screenshot from 2019-10-24 15-41-05](https://user-images.githubusercontent.com/91113/67491586-79685d00-f675-11e9-955c-febe8faa188f.png)

**Comment by davidak** [comment]
@AMDmi3 can you add another sentence?

**Comment by AMDmi3** [comment]
No, I think it's superfluous.
