### ISSUE TITLE
Status of PyPI support?

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#86]
PyPI support was added in 2016 in https://github.com/repology/repology-webapp/commit/33faee7bf1d6a2de79ff24015b2dd4ec6e4eba1a#diff-31d053584075b51c2786f5b3a4374b87.

But currently it is not displayed as repository: https://repology.org/repositories/statistics

I think it would be good as primary source for python package updates!

**Comment by AMDmi3** [comment]
https://github.com/repology/repology-updater/issues/278
