### ISSUE TITLE
Update Logs unavailable (404)

### ISSUE THREAD

**Issue by davidak** [repology/repology-webapp#89]
Many logs i checked where unavailable.

https://repology.org/repositories/updates

For example for Trisquel 6.0, Ubuntu 12.04, Solus, Parabola, nixpkgs unstable, GNU Guix, Fedora 31, Gentoo, ...

https://repology.org/log/1585935
https://repology.org/log/1585609
https://repology.org/log/1585294
https://repology.org/log/1585933
https://repology.org/log/1584969
https://repology.org/log/1585303
https://repology.org/log/1584735

Logs for Ubuntu 14.04, Void Linux x86_64, Wikidata, ... works.

**Comment by AMDmi3** [comment]
These logs are at least 3 days old, you should've at least updated the page.

**Comment by davidak** [comment]
>you should've at least updated the page.

oh, i had autorefresh disabled. my bad, sorry

**Comment by AMDmi3** [comment]
For the note, logs are currently stored for 3 days, and failures for a month.
