### ISSUE TITLE
[feature] Add maxversion parameter to badge requests

### ISSUE THREAD

**Issue by Kaffeine** [repology/repology-webapp#94]
Right now we can cut off old versions with `minversion`, but some packages have 'live dev' versions, such as 9999 or 0.99.99, etc.
As a software author, I want to exclude such numbers to show a badge with the real version (e.g. 0.2.4).
I would appreciate you to add `maxversion` param, so I'll be able to cut of unreleased version and show 0.2.4 instead of 0.99.99 or 0.2.99.

**Comment by AMDmi3** [comment]
Please give some examples. Unless some rules are missing, these versions should already be handled specially and ignored for the badges (unless there's no other version available), though you can enable them:

<a href="https://repology.org/project/aixlog/versions">
    <img src="https://repology.org/badge/vertical-allrepos/aixlog.svg?header=Default" alt="Packaging status" align="left">
</a>
<a href="https://repology.org/project/aixlog/versions">
    <img src="https://repology.org/badge/vertical-allrepos/aixlog.svg?header=allow_ignored=1&allow_ignored=1" alt="Packaging status">
</a>
