### ISSUE TITLE
Broken links to the FreeBSD.org domain when port name has special symbols in it

### ISSUE THREAD

**Issue by yurivict** [repology/repology-webapp#95]
The link to FreshPorts for the port ```graphics/png++``` is broken on https://repology.org/project/png%2B%2B/versions

It is https://www.freshports.org/graphics/png%2B%2B when the correct link is https://www.freshports.org/graphics/png++

**Comment by AMDmi3** [comment]
This is the opposite of #99. Guess we'll need to implement a special escaping filter instead of escaping globally, and use it for some links.

**Comment by AMDmi3** [comment]
> Guess we'll need to implement a special escaping filter instead of escaping globally, and use it for some links.

Done so.

Now both mageia and freebsd links are correct, some other links fixed along the way (aosc, rosa).
