### ISSUE TITLE
command line client?

### ISSUE THREAD

**Issue by anarcat** [repology/repology-webapp#96]
hello!

is there a command line client for repology? i know there's a fairly easy to use API, but it would be nice to have output that's a little more... formatted than JSON. ;)

I wrote my own prototype of something like this here:

https://gitlab.com/anarcat/scripts/raw/master/repology

but i wonder if anyone else has worked on that or if this would be welcome in this repository (or maybe the maintenance tools?)...

as an alternative, having pointers to the repology source code where i could find better ways than reinventing the wheel on this one would be welcome. in particular, i have only implemented stuff like `get foo` (equivalent of `/api/v1/project/foo`) and `search -s substring` (equivalent of `/api/v1/projects/?search=substring`) because i'm hesitant in copying the entire API endpoints in the code.

maybe providing an [OpenAPI](https://openapis.org/) endpoint would facilitate my life? :)

**Comment by AMDmi3** [comment]
I don't see any use cases for something like that (yet). It would be useful with some more integration with local packaging tools (like listing latest version for locally installed packages), but more infrastructure is needed for that. For just duplicating the website, no. Also note that API is not stable and complete yet.

**Comment by anarcat** [comment]
> I don't see any use cases for something like that (yet). It would be useful with some more integration with local packaging tools (like listing latest version for locally installed packages), but more infrastructure is needed for that. For just duplicating the website, no.

Do you mean for OpenAPI support or just a commandline tool here?

> Also note that API is not stable and complete yet.

It would be important to document that in the API docs, because right now they sure look official. :)

**Comment by AMDmi3** [comment]
> Do you mean for OpenAPI support or just a commandline tool here?

The tool. OpenAPI is just something I don't want to bother with yet, given the incomplete state of the API.

> It would be important to document that in the API docs, because right now they sure look official. :)

Sure, makes sense.

**Comment by AMDmi3** [comment]
Warning added, created separate issue related to OpenAPI (#97) for far future.

**Comment by anarcat** [comment]
so i should just take my toys and play elsewhere? ;)

shouldn't i be upstreaming that commandline tool instead of developing it on my own? is there room in this other repo maybe?

https://github.com/repology/repology-maintenance-tools

thanks!

**Comment by AMDmi3** [comment]
As I've said,
> I don't see any use cases for something like that (yet)
