### ISSUE TITLE
"Top repositories" categories is inadequate

### ISSUE THREAD

**Issue by yurivict** [repology/repology-webapp#98]
For example, the first category is "by total number of packages" and AUR is the first one there. It might seem like AUR (Arch) is the best, but it if you look into what they have - it is a lot of repetition. For example, they create a lot of "mingw-w64-*", "android-x86-64-*" repetitive packages for some reason,

The best metric for users is probably "number of unique packages", which means how many unique software titles are ported, of in other words "software availability". FreeBSD, I believe, is the leader in this important metric, but FreeBSD is only represented in the "number of fresh packages" category.

You should probably improve the categories to better reflect what users are really looking for when they use packaging systems.

**Comment by AMDmi3** [comment]
- It's not possible to automatically tell "repetition" from "unique packages", so there's no other way to make this metric more precise than by adding more merge rules
- The second metric there is less vulnerable to the duplicate issue, is it ignores stuff only present in AUR
- repology-updater#514 is more relevant for allowing FreeBSD to be represented in top categories
